#!/bin/bash
set -e

BLUE=$(tput setaf 4)
RESET=$(tput sgr 0)

# Select image
IMAGE="firedrakeproject/firedrake:2025.4.2"

# Directory where this script resides
THISDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Mount point in the container
CONTAINER_MOUNT_POINT="/home/firedrake/shared"

# Compose Docker command to be run on the host
if [ -t 0 ] ; then
    # Interactive
    DOCKER_RUN_CMD=(docker run --interactive --tty)
else
    # No input terminal
    DOCKER_RUN_CMD=(docker run)
fi
DOCKER_RUN_CMD+=(
    --rm
    --volume="${THISDIR}":${CONTAINER_MOUNT_POINT}
    --env=DISPLAY=${DISPLAY}
    --volume=/tmp/.X11-unix:/tmp/.X11-unix
    --volume="${HOME}/.Xauthority":/root/.Xauthority:ro
    --device=/dev/dri
    --workdir=${CONTAINER_MOUNT_POINT}
    ${IMAGE}
    /bin/bash
    -c
)

# Compose usage message
read -r -d '' USAGE <<EOF || true
echo "${BLUE}Repo mounted at ${CONTAINER_MOUNT_POINT}${RESET}"
echo "${BLUE}${RESET}"
echo "${BLUE}If you get error messages such as 'No protocol specified'${RESET}"
echo "${BLUE}or 'Error: Can't open display: :0.0' try running on the host:${RESET}"
echo "${BLUE}  xhost +local:docker${RESET}"
echo "${BLUE}${RESET}"
echo "${BLUE}Quick start:${RESET}"
echo "${BLUE}  python3 src/ch.py${RESET}"
echo "${BLUE}  python3 src/chns.py --benchmark single_bubble${RESET}"
echo "${BLUE}  python3 src/chns.py --benchmark two_bubbles${RESET}"
echo "${BLUE}  mpiexec -n 2 python3 src/parallel.py${RESET}"
echo "${BLUE}${RESET}"
EOF

# Don't print usage if user's command is to be executed
if [[ $# -ne 0 ]] ; then USAGE=""; fi

# Compose commands to be run in the container
read -r -d '' CONTAINER_CMD <<EOF || true
set -e

# Preserve history files
ln -s ${CONTAINER_MOUNT_POINT}/.{bash,python}_history ~/

# Preserve Firedrake cache
rm -rf \${VIRTUAL_ENV}/.cache
ln -s ${CONTAINER_MOUNT_POINT}/.cache \${VIRTUAL_ENV}/
mkdir -p ${CONTAINER_MOUNT_POINT}/.cache/tsfc/

# Inform user
$USAGE

# Run actual command with its arguments (or Bash if none given)
"\$0" "\$@"
EOF

# Run actual commands with provided command-line parameters
"${DOCKER_RUN_CMD[@]}" "${CONTAINER_CMD}" "$@"
